In [19]:
import numpy as np
import pandas as pd

In [19]:
arr1 = np.array([[1,2,3,4],[1,2,3,5]], dtype = int)
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 5]])

In [11]:
np.shape(arr1)

(2, 4)

In [14]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[7, 9, 0],
       [6, 6, 3],
       [7, 9, 9]])

In [17]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [28]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [34]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[7, 9, 0],
       [7, 0, 8],
       [4, 5, 1]])

In [45]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#индекс можно указывать в отдельных квадратных скобках или внутри одной пары скобок через запятую
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[1][2]
my_array[1,2]

12

In [116]:
#Упражнения

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

a = big_secret[:, -1]
b = 0
for i in a:
    b +=i
print(round(b,2))

q2 = big_secret[:, :5]
b =q2[0,0]+ q2[1,1]+q2[2,2]+ q2[3,3]+ q2[4,4]
print(round(b,2))

q3 = big_secret[:, -5:]
b =q3[0,0] * q3[1,1] * q3[2,2] * q3[3,3] * q3[4,4]
print(b)


for y in range(0, 5):
       for x in range(0, 51):
            if (y%2 == 0) and (x%2 == 0):
                big_secret[y,x] = -1 
            elif (y%2 !=0) and (x%2 != 0):
                big_secret[y,x] = 1 

big_secret[:,:5]


3154.33
121.37
341505315559.2347


array([[-1.        , 10.        , -1.        , 56.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        ,  1.        , -1.        ,  9.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        , 10.        , -1.        , 56.        , -1.        ]])

In [2]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [17]:
q = np.cos(great_secret[0])
print(q[0]+q[1]+q[2])

q = great_secret[great_secret>50] #умма элементов массива great_secret, значение которых больше 50?
print(np.sum(q))

print (great_secret.flatten()[150]) #great_secret в одномерную форму. 150 index

np.sum(np.sort(great_secret, axis = 0)[99]) #Отсортируйте значения столбцов массива great_secret по возрастанию. + sum

0.16006721889793019
5470.0
7.0710678118654755


115.12148016521353

In [30]:
students = pd.read_excel('students.xlsx')
print(students)
students = np.array(students)


mean = np.mean(students[:,-1])
mean

median = np.median(students[:,-1])
median

   ID (номер в журнале)  Рост, см  Масса тела, кг  Средний балл
0                     1       135              34           4.0
1                     2       160              43           5.0
2                     3       163              40           4.3
3                     4       147              44           5.0
4                     5       138              41           4.7
5                     6       149              54           3.9
6                     7       136              39           4.2
7                     8       154              48           4.9
8                     9       137              35           3.7
9                    10       165              60           4.6


4.449999999999999

In [50]:
np.median(students[:,2]) #медианное значение массы тела школьников
np.mean(students[:,2]) - np.median(students[:,2]) # разница среднего и медианы

corr = np.corrcoef(students[:,1],students[:,2]) # коэффициент корреляции
print(corr)

corr = np.corrcoef(students[:,2],students[:,-1]) 
print(corr)

corr = np.corrcoef(students[:,1],students[:,-1]) 
print(corr)

np.std(students[:,1]) #рост, стандартное отклонение std
print(f'В результате разброс в росте большинства учеников составляет более {round(np.std(students[:,1]),2)} см от среднего арифметического. ')

np.std(students[:,3])
(np.std(students[:,2]))**2 #дисперсия

[[1.         0.64314431]
 [0.64314431 1.        ]]
[[1.         0.29801325]
 [0.29801325 1.        ]]
[[1.         0.46293714]
 [0.46293714 1.        ]]
В результате разброс в росте большинства учеников составляет более 11.08 см от среднего арифметического. 


60.36

In [56]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])


In [133]:
my_sin = np.sin(my_array)
np.sum(my_sin)

my_sin[1:4,1:4] = np.ones((3,3))
np.sum(my_sin)
q = my_sin[:,:4].reshape((10, 2)) 
np.sum(q[:,0])

bigdata = np.array([x*x for x in range(100, 1001) if x%2!= 0])
np.std(bigdata)
mask1 = np.array([1,0,1,0,1,0,1,0], dtype = bool)

chet = bigdata[::2]
nechet = bigdata[1::2]
np.corrcoef(bigdata[::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])

In [2]:
a = dfsdf
a

NameError: name 'dfsdf' is not defined